FROM docker:27-cli

RUN apk add --no-cache bash tzdata curl docker-compose

WORKDIR /app

COPY scheduler.sh /app/scheduler.sh
COPY crontab /etc/crontabs/root
RUN chmod +x /app/scheduler.sh

# Logs directory
RUN mkdir -p /app/logs

CMD ["crond", "-f", "-l", "2"]